### ISSUE TITLE
mu_basecore's VERSIONINFO support is not currently building on GCC

### ISSUE THREAD

**Issue by out0xb2** [microsoft/mu#105]
Placeholder, more details to follow...

**Comment by martinezjavier** [comment]
I have proposed microsoft/mu_basecore#79 as a fix for this issue.

**Comment by martinezjavier** [comment]
> I have proposed [microsoft/mu_basecore#79](https://github.com/microsoft/mu_basecore/pull/79) as a fix for this issue.

I closed this since the approach wasn't correct at the end. Hopefully at least contains useful information for someone more familiar with all this to attempt fixing the issue.
