### ISSUE TITLE
Conf folder not included in .gitignore

### ISSUE THREAD

**Issue by unkemptArc99** [microsoft/mu#112]
While building the Mu_plus, I noticed that the Conf folder gets generated for all the tools settings (like VS2019 or GCC5). I think since this is a folder which gets generated on build, we should include this in the .gitignore file.

Please feel free to add any other opinions over this.

**Comment by spbrogan** [comment]
I agree but looking at recent releases I see that there. 
Example: https://github.com/microsoft/mu_plus/blob/3f7baeb3d957f922c4d51d49cb10ea557b2cfd9a/.gitignore#L13

Thanks
