### ISSUE TITLE
MU_PLUS: Document for "Allow local user to change UEFI settings" in DFCI

### ISSUE THREAD

**Issue by NickWangInsyde** [microsoft/mu#114]
There is "Allow local user to change UEFI settings" setting in DFCI config profile, but these is no document to describe which UEFI variable save this setting value.

For example: I can see "CPU and IO virtualization" description in [here](https://microsoft.github.io/mu/dyn/mu_plus/DfciPkg/Docs/PlatformIntegration/DfciGroups/#dfci-standard-groups-for-oem-extension) or DfciSettings.h, so I know "Dfci.CpuAndIoVirtualization.Enable" UEFI variable save this setting value.

**Comment by spbrogan** [comment]
The allow option is handled by permission.  
DFCI includes settings, identities, and permissions.  The MDM sets each of these.  The permissions are set differently depending on how the administrator has set that policy.    Hope that helps.
