### ISSUE TITLE
MU_PLUS: UEFI variable "_SPP" is modified every POST if IS_OWNER_IDENTITY_ENROLLED(IdMask) return FALSE.

### ISSUE THREAD

**Issue by NickWangInsyde** [microsoft/mu#116]
If IS_OWNER_IDENTITY_ENROLLED(IdMask) returns FALSE in CheckForAuthenticationProtocol(), UEFI variable "_SPP" will be updated   every POST because Var->SavedOn is different.

Side effect: Every POST, it makes available size in Flash Part variable region less. It will trigger variable reclaim process at someone POST and makes POST time increase. Basically, if system state/configuration is not changed, available size in Flash Part variable region should be the same.

Suggestion: In CheckForAuthenticationProtocol(), it should not modify "_SPP" if OWNER_IDENTITY_ENROLLED state is not changed.

**Comment by out0xb2** [comment]
Fixed in https://github.com/microsoft/mu_plus/commit/431080dc42c27292236f8fa8391fe7271c2f4b63
