### ISSUE TITLE
UEFI on Surface Go blocks non-Windows USB

### ISSUE THREAD

**Issue by WhiteCzar** [microsoft/mu#118]
I am led to understand from your documentation that this is basically the upstream development of the MS Surface UEFI, so I'll repeat here the question and issue that I raised on MS Answers forums here: https://answers.microsoft.com/en-us/surface/forum/all/surface-go-boot-from-usb/4668ec45-af97-4766-9130-53ff75e2e0e2

Can anyone explain to me what are the technical reasons that Surface Go (eMMC version) UEFI refuses to directly boot any UEFI bootable USB other than that with a Windows OS on it?

The issue is as follows: assume you want to install a GNU/Linux OS on your Surface Go. You create a bootable USB with Rufus, you insert it in the USB-C slot and you turn on your system while holding down the volume-down button to toggle the alternate-boot sequence (that's of course enabled in your firmware). But this doesn't seem to boot anything other than whatever OS is already installed on your system, not the LiveUSB.

You then boot into your UEFI settings and change the boot order manually, setting the USB on top. You boot up, but - alas! - USB still won't boot. Finally you boot up your Windows and go to advanced restart. From there you try to boot from USB, and yet again if you try selecting the option to boot from EFI USB the system will simply reboot into the OS already on your Surface.

You do the advanced restart again but this time instead of EFI USB you select the weird named option Linpus Lite - and finally you are able to boot from your GNU/Linux USB (Which is any distro - I tried with Ubuntu, Fedora and PopOS!).

The above jumping though hoops demonstrates that Surface Go doesn't boot non-Windows bootable USBs directly for some reason. I wanna know the technical reason why. By the way, this has got nothing to do with Secure Boot as it can be turned on or off, it doesn't matter.

Upon further tinkering, with `efibootmgr` I was able to ascertain that whenever a non-Windows bootable USB gets inserted, there appears a new efi boot entry named 'Linpus Lite', but when a Windows bootable USB gets inserted, no new boot entry appears; instead the always-present 'EFI USB drive' boot entry is the Win bootable USB entry. Why is that?

**Comment by WhiteCzar** [comment]
Here's another guy describing the same problem. (The first point)

https://medium.com/@TheBitStick/fedora-31-on-the-surface-go-f81dbb9fa91b

**Comment by out0xb2** [comment]
Many Surface devices have a UEFI based upon Project Mu.  However, Surface Go's UEFI is not​ based upon Project Mu, and as such, Project Mu representatives are unable to answer questions about it.

Microsoft Surface support channels are the best venue for answers to Surface Go UEFI questions.  

Kind regards,
Project Mu team

**Comment by WhiteCzar** [comment]
Gotcha!
Thanks anyway
