### ISSUE TITLE
How to modify or specify a logo for UEFI?

### ISSUE THREAD

**Issue by goxia** [microsoft/mu#119]
How we modify or specify a UEFI logo, and the steps are friendly.

**Comment by spbrogan** [comment]
Project Mu isn't really a platform.  It is the core UEFI code used for many platforms. 

In your platform you would specify a driver that loads the logo.  
We do have 1 virtual platform (QEMU based) that you can use as a demo and in that platform you could change the logo here. 
 
https://github.com/microsoft/mu_tiano_platforms/blob/19d8af9a969a802cba9664723eeed0911c349465/Platforms/QemuQ35Pkg/QemuQ35Pkg.fdf#L539

This is where the default logo comes from.
https://github.com/microsoft/mu_oem_sample/tree/release/202202/OemPkg/FrontPage/Resources

Anyway that is just sample code that we would expect a "real" platform to change or customize.
