### ISSUE TITLE
How to compile UEFIPayload?

### ISSUE THREAD

**Issue by Ratatouilledummie** [microsoft/mu#121]
in twitter a Microsoft Engineer have build the UEFIPayload with secure boot for coreboot with TPM Work 
Sorry for this dummie issue but how to compile?

**Comment by spbrogan** [comment]
Project Mu is the core of the UEFI code base and also has repos with example platforms like qemu.  https://github.com/microsoft/mu_tiano_platforms/tree/release/202202

But we don't have a repo that builds a UEFI payload.  That could be done with the Project Mu core but the payload (which is the "platform")  would be hosted somewhere else.  Sorry i couldn't provide more info.
