### ISSUE TITLE
Incremental build error

### ISSUE THREAD

**Issue by charvatjiri** [microsoft/mu#122]
Hello,
it was reported by one of our customers, that incremental build does not work. We tracked it down to the GNUmakefile
RELEASE_GCC5/AARCH64/ArmPlatformPkg/PrePi/PeiUniCore/GNUmakefile
where a dependency is missing: instead of:

> $(FFS_OUTPUT_DIR)/$(MODULE_GUID).efi :
> 	test -f $(OUTPUT_DIR)/ArmPlatformPrePiUniCore.efi && $(CP) $(OUTPUT_DIR)/ArmPlatformPrePiUniCore.efi $(FFS_OUTPUT_DIR)/$(MODULE_GUID).efi
> 
the incremental build works fine with:
> $(FFS_OUTPUT_DIR)/$(MODULE_GUID).efi : $(OUTPUT_DIR)/ArmPlatformPrePiUniCore.efi
> 	test -f $(OUTPUT_DIR)/ArmPlatformPrePiUniCore.efi && $(CP) $(OUTPUT_DIR)/ArmPlatformPrePiUniCore.efi $(FFS_OUTPUT_DIR)/$(MODULE_GUID).efi
>
It means that copy will happen not only if the destination file is missing, but also if the source file (=makefile rule dependency) has changed. (Possibly similar issue for *.map file above in the same GNUmakefile).
I can provide more details if needed, and can debug the whole GNUmakefile generation process in mu_basecore/BaseTools/Source/Python. But it is too big to debug for external person so hopefully somebody can look into it.
Can this be fixed?

**Comment by spbrogan** [comment]
Opened bug with tianocore https://github.com/tianocore/edk2-basetools/issues/38
