### ISSUE TITLE
MdeModulePkg: MdeModulePkg/Logo/LogoDxe.inf fails to compile

### ISSUE THREAD

**Issue by spbrogan** [microsoft/mu#35]
Fails to build with error: 

MdeModulePkg\Logo\Logo.c(34): error C2065: 'IMG_LOGO': undeclared identifier
INFO - MdeModulePkg\Logo\Logo.c(33): error C2099: initializer is not a constant
INFO - NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\cl.exe"' : return code '0x2'

**Comment by qiuguoguang** [comment]
![base_core_logo](https://user-images.githubusercontent.com/13567583/68570027-9933b980-049a-11ea-913e-3c607b62174b.PNG)   Logo.idf  need included in logo module source part either, which define the needed image token;

**Comment by spbrogan** [comment]
upstream fixed and integrated
