### ISSUE TITLE
Remove "edit" link for dynamic documentation pages

### ISSUE THREAD

**Issue by spbrogan** [Microsoft/mu#38]
Add meta tag so that the edit link doesn't show up.  Edit link takes you to a 404.

**Comment by GOVINDDIXIT** [comment]
@spbrogan  I like to work on this issue

**Comment by spbrogan** [comment]
The goal of this is to remove the Edit link only for the Dyn content.  The "Code repositories" link on left shows content pulled from other Project Mu repositories.   I was thinking of adding the meta tag on the dynamic md files.

**Comment by spbrogan** [comment]
Currently looks like there is no MkDocs configuration option for this.  Closing as won't fix.
