### ISSUE TITLE
coreboot open source BIOS is already there. Why keep reinventing the wheel?

### ISSUE THREAD

**Issue by informer2016** [Microsoft/mu#52]
coreboot open source BIOS is already there and supports a lot of real motherboards. https://coreboot.org/status/board-status.html Instead of reinventing the wheel as "mu" it would have been more efficient to join our forces. I am addressing those 25 people who thought this repository is worthy of forking and would like to know their opinions : @Abhimanyu121 , @Shreya-khandelwal , @abhiraj963 , @adi23arora , @akshay196 , @c-stauffer , @DalavanCloud , @FY1043031060 , @gauravano , @gus33000 , @Justinha , @Man-Jain , @mknutsen , @moulikcipherX  , @netroby , @panwalas, @pristineVedansh , @ramyhhh , @ritwik787 , @sanchittanwar7 , @sk9331657  , @skshetry , @StefMa , @uzerjamal , @vbhaip

**Comment by wille-io** [comment]
Project Mu is an UEFI implementation. Coreboot can already be used with TianoCore, but TianoCore has its problems that Mu will address. 
But yes I agree on the "we should all work together" part of your concern.

**Comment by informer2016** [comment]
@wille-io Thank you for reply. But is UEFI a system requirement nowadays? Lets clone the coreboot board_status repository with the reports containing the coreboot configs submitted by the coreboot users , and estimate the popularity of SeaBIOS payload _(modern legacy BIOS)_ compared to everything else:
```
git clone http://review.coreboot.org/board-status
cd ./board-status
find . -type f -print0 | xargs -0 grep "CONFIG_PAYLOAD_SEABIOS=y" | wc -l
7750
find . -type f -print0 | xargs -0 grep "# CONFIG_PAYLOAD_SEABIOS is not set" | wc -l
718
```
More than 10x times difference in favor of SeaBIOS . `# CONFIG_PAYLOAD_SEABIOS is not set` = something else than SeaBIOS has been selected, e.g. `CONFIG_PAYLOAD_GRUB2` or `CONFIG_PAYLOAD_NONE` used by the people who would like to add an unknown payload later - maybe Tianocore, maybe not

**Comment by vexx32** [comment]
That's interesting trivia, but it lacks any sufficiently meaningful data points, as all it has are the numbers  of submissions, essentially, which doesn't indicate how much they're actually used in the long run, nor why that particular (is 'framework' the right term? Tired brain...) Submission opted for SeaBIOS.

Anyway, while your opinion may be very much valid and valuable, I think it rather unlikely that an entire Microsoft product team will simply drop everything they're working on to file a few pull requests on an established repo. Their intent insofar as I can infer from the blog post is probably more along the lines of "we're trying something new to see how good we can make it" more than anything else.

That doesn't mean this discussion doesn't have merit, but I personally don't think it's going to make much of a *difference* in this repo. I'm interested to hear from anyone on the Microsoft Mu team who would like to comment, of course.

**Comment by informer2016** [comment]
@vexx32 Thank you for reply! Small clarification: although I used to call coreboot an "open source BIOS" to simplify the things, in fact coreboot just initializes the hardware and then transfers control to some add-on _("payload")_ which provides a user interface.
SeaBIOS payload gives a simple convenient boot menu, perfectly following the Unix philosophy of "Do One Thing and Do It Well" - so it's not surprising to me that so many people are using it, also considering that SeaBIOS is just 50k lines of clean code _(of which maybe just a few thousands would be active at specific configuration)_
==> and is quite easy to modify to add the new features without getting lost: being a newbie programmer, with this [small patch](https://mail.coreboot.org/pipermail/seabios/2017-June/011416.html) I added support for large boot menus with up to 35 entries, although it hasn't been merged yet . Also I don't know any OS which are UEFI only , and as user of PC with coreboot+SeaBIOS flashed into BIOS chip as its' proprietary firmware replacement, I could say that it works perfectly so far 
![sb-menu](https://user-images.githubusercontent.com/26509528/50286638-131d1780-0471-11e9-83b3-eb6208ec681b.jpg)

**Comment by out0xb2** [comment]
@informer2016 , you asked, "is UEFI a system requirement nowadays?".  UEFI has been a Windows Logo/Certification/Compatibility Requirement starting with Windows 8.0, 5+ years ago.  Among other features, it provided support for large boot drives and Secure (Authenticated) Boot, and more security and functional features have been added since that time.  Coreboot+SeaBIOS may meet your requirements, but it does not meet the past 5+ years of Windows Requirements https://aka.ms/whcr.  

Project Mu targets UEFI developers and systems, demonstrating efficient methods for developing and maintaining UEFI code, and also gives many Microsoft UEFI features to the OSS community.

**Comment by informer2016** [comment]
@out0xb2 This "MS Secure Boot" is a Restricted Boot in reality - https://www.fsf.org/campaigns/campaigns-summaries#secureboot . If you would like to try a truly Secure Boot which is not restricting your freedom, there's a coreboot `heads` add-on, which isn't MS™ (c) approved but is more secure. And there is nothing UEFI can do which coreboot+SeaBIOS can't : SeaBIOS is a _modern_ legacy-style BIOS and can boot from large hard drives. coreboot already supports a lot of motherboards - https://coreboot.org/status/board-status.html - OSS community is perfectly fine without Microsoft UEFI

![restricted-boots](https://user-images.githubusercontent.com/26509528/50293849-947ea500-0485-11e9-827d-24e7fcabce08.jpg)

**Comment by vexx32** [comment]
@informer2016 in the end, nobody's _forcing_ you or anyone else to contribute here if you don't want to. 

Judging by the recent blog post, Microsoft want a modern-*looking* bootloader as well as one that uses modern code where the user can't see it.

And sure, the OSS community may be "fine" without this being available, but it's been my experience that the more decently well-written and documented code out there, the quicker all parties in the field tend to innovate and recombine ideas.

There's nothing wrong with variety, and nothing wrong with an alternative. If you don't want to use and contribute, that is, ultimately, your own prerogative.

I, for one, am rather interested to see where this goes and what it leads to. What it is _now_ is practically irrelevant in the larger picture, but it isn't a bad starting point, and has some potential to lead to some interesting places.

**Comment by spbrogan** [comment]
@informer2016 
I think this is a great question and I would have hoped our https://microsoft.github.io/mu/ site would have answered this.  If nothing else, we can update the FAQ page with something to address "Why UEFI".  Simple enough our requirements are to use UEFI.  UEFI is the boot firmware used in the majority of today's PCs targeting commercial OSes such as Microsoft Windows 10.  UEFI has, and continues to be developed to support the widest variety of modern operating systems with the fullest feature set required by todays devices and todays customers.  Coreboot, SeaBIOS, LinuxBoot, Libreboot, and other boot firmware all have their place but again this project is focused on UEFI.  

Also note we are not attempting to "re-invent the wheel".  We are very clearly a derivative of TianoCore EDK2 with a strong commitment to stay aligned to that project.  We have made changes within this project we believe bring value to the UEFI ecosystem and want to share those changes.  Some of our changes are too extensive to make to the existing Edk2 project without major disruption and will always stay here while other minor code changes are on a path to be upsteamed in Tianocore Edk2.  

Thanks for your interest in the project.
