### ISSUE TITLE
Add FAQ entry for common questions or misunderstandings

### ISSUE THREAD

**Issue by spbrogan** [microsoft/mu#53]
Over the past couple days I have seen a lot of questions and misunderstandings that Project Mu should try to clarify. 
* Why UEFI?
* Can I replace the firmware on my product with this? (Surface device, etc)
* What can i build with this? 
* Who is this project useful for (target audience)?

**Comment by matthewfcarlson** [comment]
I'm working on this

**Comment by riverar** [comment]
Any updates on this? It's still unclear how to set up a working dev environment and/or compile a module. The documentation is incomplete.

**Comment by out0xb2** [comment]
@riverar ,
An older example is here: 
https://github.com/ms-iot/MU_PLATFORM_NXP

Newer (but not quite finished) one is here:
https://github.com/matthewfcarlson/mu_rpi 

A doc in progress here:
https://github.com/tianocore/edk2-pytool-extensions/pull/96/files

Hope to close the loop soon, a few more details to polish...
