### ISSUE TITLE
How is PcdCurrentPointerState value handled in MsGraphicsPkg? It looks like should not be zero. 

### ISSUE THREAD

**Issue by tsunghowu** [Microsoft/mu#54]
Hi, I am trying to build mu_plus/MsGraphicsPkg into OvmfPkg and see how it goes in QEMU. But I run into an issue that in UiDisplayMenu, the PCD CurrentPointerState is always zero and it looks like the pointer should be pointing to something in the memory and should not be zero. Is there any missing library/Dxe driver missing in MsGraphicsPkg? 

EFI_STATUS
UiDisplayMenu (IN FORM_DISPLAY_ENGINE_FORM *FormData) {
    EFI_STATUS                    Status                  = EFI_SUCCESS;
    DISPLAY_ENGINE_SHARED_STATE   *MasterFrameSharedState = (DISPLAY_ENGINE_SHARED_STATE *)(UINTN)PcdGet64(PcdCurrentPointerState);

Peter

**Comment by spbrogan** [comment]
The DisplayEngineDxe driver from MsGraphicsPkg has some expected dependencies on the "UEFI Front Page app".  The best way to see this is to leverage our example front page app.   https://github.com/Microsoft/mu_oem_sample/tree/release/201808/OemPkg/FrontPage

**Comment by tsunghowu** [comment]
Thanks. I can see the page(displaying Project MU, PC Information) after loaded FrontPage driver.
-Peter
