### ISSUE TITLE
PlatformBuild submodule update doesn't return an error code

### ISSUE THREAD

**Issue by jorticus** [microsoft/mu#57]
The Platform Build --UPDATE --SETUP commands try to checkout and update the submodules in the repository. If it encounters an error (eg. you haven't pushed a commit to the submodule, the server is down, etc.) the script continues and returns a successful exit code.

This causes issues with automated build systems as the build will continue and try to build the project, and fail much later because the submodule was never actually checked out.

repo:mu_pip_environment

**Comment by spbrogan** [comment]
mu_pip modules are no longer supported.  
Please check out https://github.com/tianocore/edk2-pytool-extensions for continued development
