### ISSUE TITLE
DocBuild: add support for *Pkg/Docs folder for Package-wide documentation

### ISSUE THREAD

**Issue by out0xb2** [microsoft/mu#78]
Sometimes a Package needs more overview documentation than reasonably should be in 1 markdown file in the root folder.  Add support for a Docs subdirectory to contain this Package-wide documentation that is promoted in the twiddle tree, then demote the individual component docs to a subfolder in the twiddle tree.

**Comment by spbrogan** [comment]
#79 is my attempt at this.
