### ISSUE TITLE
DFCI needs documentation for testing HTTP recovery from the BIOS menu 

### ISSUE THREAD

**Issue by kevindavisinsyde** [microsoft/mu#88]
Is there any testing available for the Mu DFCI implementation for a BIOS Vendor?

**Comment by out0xb2** [comment]
Hi Kevin, have you taken a look at https://github.com/microsoft/mu_plus/tree/release/202002/DfciPkg/UnitTests ?
There is an end-to-end test based upon the open source Robot Framework.  However, configuring the automation is not a requirement, inspecting the test source you can build USB keys with shell apps and data to do initial testing.  Feel free to ping us on the Teams for faster dialog turnaround.

**Comment by kevindavisinsyde** [comment]
I saw that and was going to point it out to Nick today.  Thanks

Kevin D Davis
Security Strategist
Insyde Software
Phone: 503-310-2222

**Comment by NickWangInsyde** [comment]
Hi Jeremiah,

  Yes, I integrated DFCI into UEFI firmware and run and pass all test cases in the UnitTests/DfciTests.
Before release solution to customer, I also want to verify DFCI through Microsoft Intune, which will communicate with Windows Autopilot services.  For using Microsoft Intune, the PCs with DFCI should be registered to the Windows Autopilot service.

  My question is how to test DFCI through Microsoft Intune for BIOS vendor. Do I need to register the test PC to Windows Autopilot service ? Or is there any way(for example: set specified Manufacturer/ProductName/SerialNumber) without registration ?

**Comment by out0xb2** [comment]
Hi Nick,
Have you tested the manual recovery workflow, where you go to BIOS menu > Management > Recovery > HTTP and performed recovery against test recovery server mikeytbds3 ?  
If you want faster turnaround time on discussions, feel free to chat on our Teams channel, I believe you should have an invitation in your inbox.

**Comment by NickWangInsyde** [comment]
Hi Jeremiah,

Got it. I replied in the Teams DFCI channel. Thank you.

**Comment by out0xb2** [comment]
Changing the title to the next step of testing which is HTTP Recovery, after that, contact us on Teams to discuss the Intune Autopilot testing
