### ISSUE TITLE
Consolidate the multiple copies of UefiVariablesSupportLib.py in MU_PLUS

### ISSUE THREAD

**Issue by out0xb2** [microsoft/mu#89]
There are 2 copies of UefiVariablesSupportLib.py in MU_PLUS.

1. [UefiTestingPkg copy](https://github.com/microsoft/mu_plus/blob/42bc853ecb2511f0684a5553f3c671e8b141ac23/UefiTestingPkg/AuditTests/UefiVarLockAudit/Windows/UefiVariablesSupportLib.py)
2. [DfciPkg copy](https://github.com/microsoft/mu_plus/blob/42bc853ecb2511f0684a5553f3c671e8b141ac23/DfciPkg/UnitTests/DfciTests/Support/Python/UefiVariablesSupportLib.py)

Consider consolidation _**or**_ move to a PyTools Library?

**Comment by corthon** [comment]
Ewww... I thought that already *was* in one of the edk2tools packages?
If not, yes, we should move it.

**Comment by matthewfcarlson** [comment]
I feel like you could also make the case that this belongs in pytool extensions. But yes. I strongly agree this should be in one of the pytools

**Comment by spbrogan** [comment]
So we have talked about adding somethign like this https://github.com/microsoft/mu_plus/blob/release/202002/UefiTestingPkg/AuditTests/UefiVarLockAudit/Windows/UefiVariablesSupportLib.py   to a location like  here: https://github.com/tianocore/edk2-pytool-library/tree/master/edk2toollib/windows

But this code carries significant dependencies.  It needs access to win32apis.  This requires installing other modules some of which are not small.
