### ISSUE TITLE
Reference to mkdocs-macros in documentation

### ISSUE THREAD

**Issue by fralau** [microsoft/mu#90]
In the documentation page [Documentation Sample...](https://microsoft.github.io/mu/DeveloperDocs/doc_sample_test/) the mention of **mkdocs-macros** refers to the [github site](https://github.com/fralau/mkdocs_macros_plugin).

As the maintainer of that project, I just wanted to let you know that there is now a very detailed [documentation on mkdocs-macros available on readthedocs](https://mkdocs-macros-plugin.readthedocs.io/en/latest/). You may want the refer to it, especially since there is information that specifically applies to large projects.

**Comment by spbrogan** [comment]
Thanks for pointing this out.
